---
services:
  ham-quiz:
    image: ham-quiz:1.0.6
    container_name: ham_quiz
    environment:
      - TZ=America/Chicago
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - type: bind
        source: ./logs
        target: /opt/docker/logs
      - type: bind
        source: ./conf
        target: /opt/docker/conf
    restart: unless-stopped
